package me.fungames.jfortniteparse.ue4.assets.objects.meshes

import me.fungames.jfortniteparse.ue4.objects.engine.FWeightedRandomSampler

typealias FStaticMeshSectionAreaWeightedTriangleSampler = FWeightedRandomSampler