/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OodleKraken */

#ifndef _Included_OodleKraken
#define _Included_OodleKraken
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OodleKraken
 * Method:    KrakenDecompress
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_OodleKraken_KrakenDecompress
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
